### ISSUE TITLE
Segfault when trying to restore renamed fucntions

### ISSUE THREAD

**Issue by muteor** [php-test-helpers/php-test-helpers#28]
Hi I have a slightly strange problem with PHP 5.4 and test helpers, when renaming and restoring functions in a loop I get either `Fatal error: Cannot call overloaded function for non-object` or a segmentation fault. This previously worked ok in 5.3.

Added test:

``` PHP
--TEST--
rename_function() and user-defined functions and restore afterwards
--SKIPIF--
<?php
if (!extension_loaded('test_helpers')) die('skip test_helpers extension not loaded');
?>
--FILE--
<?php
function foo()
{
    print 'foo';
}

$backups = array();

for ($i=0;$i<2;$i++) {
        $backups['foo'] = 'backup' . $i;
        // Stash org
        rename_function('foo', $backups['foo']);
        // Make new
        eval("function foo() { return 'bar'; }");
        echo foo();
        // Ditch it
        rename_function('foo', 'foo_dead_' . $i);
        // Restore it
        rename_function($backups['foo'], 'foo');
}

foo();
--EXPECT--
barbarfoo
```

Run report:

```
=====================================================================
PHP         : /usr/bin/php
PHP_SAPI    : cli
PHP_VERSION : 5.4.4-14+deb7u7
ZEND_VERSION: 2.4.0
PHP_OS      : Linux - Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.51-1 x86_64
INI actual  : /etc/php5/cli/php.ini
More .INIs  : /etc/php5/cli/conf.d/10-pdo.ini,/etc/php5/cli/conf.d/20-mcrypt.ini,/etc/php5/cli/conf.d/30-tools.ini,/etc/php5/cli/conf.d/redis.ini
CWD         : /root/php-test-helpers
Extra dirs  :
VALGRIND    : Not used
=====================================================================
TIME START 2014-02-25 11:35:16
=====================================================================
SKIP Loading test_helpers as zend_extension [tests/load_as_zend_extension-php5.5.phpt] reason: this test is for PHP 5.5+.
PASS Loading test_helpers as zend_extension [tests/load_as_zend_extension.phpt]
PASS rename_function() and user-defined functions [tests/rename_function.phpt]
FAIL rename_function() and user-defined functions and restore afterwards [tests/rename_function_and_restore.phpt]
XFAIL rename_function() and internal functions [tests/rename_internal_function.phpt]   XFAIL REASON: Not yet implemented
PASS rename_method() and user-defined functions [tests/rename_method.phpt]
PASS set_exit_overload() [tests/set_exit_overload.phpt]
PASS set_exit_overload() with an uncaught exception [tests/set_exit_overload_exception.phpt]
PASS debug_print_backtrace() should work inside the callback. [tests/set_new_overload_backtrace.phpt]
PASS A closure can be registered as a callback with set_new_overload() [tests/set_new_overload_closure.phpt]
XFAIL Callback for the new operator is invoked for non-existing classes [tests/set_new_overload_error_non_existing_class.phpt]   XFAIL REASON: Currently not supported by the implementation but nice to have
PASS A fatal error is triggered when the class returned by the callback does not exist [tests/set_new_overload_error_return_non_existing_class.phpt]
PASS A warning is triggered when the callback passed to set_new_overload() is not defined [tests/set_new_overload_error_undefined_callback.phpt]
PASS A function can be registered as a callback with set_new_overload() [tests/set_new_overload_function.phpt]
PASS A functor can be registered as a callback with set_new_overload() [tests/set_new_overload_functor.phpt]
PASS set_new_overload() can be called multiple times and unset_new_overload() works [tests/set_new_overload_multiple.phpt]
PASS A non-static method can be registered as a callback with set_new_overload() [tests/set_new_overload_non_static_method.phpt]
PASS A non-static method of the same object can be registered as a callback with set_new_overload() [tests/set_new_overload_non_static_method_same_object.phpt]
PASS A private method can be registered from the right context with set_new_overload() [tests/set_new_overload_private_method.phpt]
PASS A static method can be registered as a callback with set_new_overload() [tests/set_new_overload_static_method.phpt]
PASS set_new_overload() can be called after unset_new_overload() [tests/set_new_overload_unset_reset.phpt]
PASS set_exit_overload() [tests/unset_exit_overload.phpt]
=====================================================================
TIME END 2014-02-25 11:35:17

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   50
---------------------------------------------------------------------

Number of tests :   22                21
Tests skipped   :    1 (  4.5%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    1 (  4.5%) (  4.8%)
Expected fail   :    2 (  9.1%) (  9.5%)
Tests passed    :   18 ( 81.8%) ( 85.7%)
---------------------------------------------------------------------
Time taken      :    1 seconds
=====================================================================

=====================================================================
EXPECTED FAILED TEST SUMMARY
---------------------------------------------------------------------
rename_function() and internal functions [tests/rename_internal_function.phpt]  XFAIL REASON: Not yet implemented
Callback for the new operator is invoked for non-existing classes [tests/set_new_overload_error_non_existing_class.phpt]  XFAIL REASON: Currently not supported by the implementation but nice to have
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
rename_function() and user-defined functions and restore afterwards [tests/rename_function_and_restore.phpt]
=====================================================================

You may have found a problem in PHP.
This report can be automatically sent to the PHP QA team at
http://qa.php.net/reports and http://news.php.net/php.qa.reports
This gives us a better understanding of PHP's behavior.
If you don't want to send the report immediately you can choose
option "s" to save it.  You can then email it to qa-reports@lists.php.net later.
Do you want to send this report now? [Yns]: n
```

Config (also tried without xdebug and with test helpers loaded as non zend module):

```
root@debian:~/php-test-helpers# cat /etc/php5/conf.d/30-tools.ini
zend_extension=/usr/lib/php5/20100525/xdebug.so
zend_extension=/usr/lib/php5/20100525/test_helpers.so
```

Test result:

```
root@debian:~/php-test-helpers# cat tests/rename_function_and_restore.diff
001+ bar
001- barfoo
002+ Fatal error: Cannot call overloaded function for non-object in /root/php-test-helpers/tests/rename_function_and_restore.php on line 15

root@debian:~/php-test-helpers# tests/rename_function_and_restore.sh
barSegmentation fault
```

Backtrace from: tests/rename_function_and_restore.sh

```
#0  0x00007fcf8da7c86f in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x0000000000642c0e in xbuf_format_converter (xbuf=0x7fff71efb1c0, fmt=0x1 <Address 0x1 out of bounds>, ap=0x0) at /tmp/buildd/php5-5.4.4/main/spprintf.c:576
#2  0x0000000000643a04 in vspprintf (pbuf=0x7fff71efb240, max_len=1024, format=0xffffffffffbc9353 <Address 0xffffffffffbc9353 out of bounds>, ap=0x18) at /tmp/buildd/php5-5.4.4/main/spprintf.c:799
#3  0x000000000063cea8 in php_error_cb (type=1, error_filename=0x7fcf90684f30 "/root/php-test-helpers/tests/rename_function_and_restore.php", error_lineno=15, format=0x18 <Address 0x18 out of bounds>, args=0x552e42475f6e653d)
    at /tmp/buildd/php5-5.4.4/main/main.c:935
#4  0x000000000055bbe0 in soap_error_handler (error_num=-1872212176, error_filename=0x0, error_lineno=32719, format=0x7fff71efb970 "\020", args=0x0) at /tmp/buildd/php5-5.4.4/ext/soap/soap.c:2219
#5  0x000000000069fb74 in zend_error (type=1, format=0xa8fd98 "Non-static method %s::%s() cannot be called statically") at /tmp/buildd/php5-5.4.4/Zend/zend.c:1098
#6  0x00000000007476e0 in zend_do_fcall_common_helper_SPEC (execute_data=0x7fcf90652060) at /tmp/buildd/php5-5.4.4/Zend/zend_vm_execute.h:603
#7  0x0000000000700b37 in execute (op_array=0x7fcf90684d90) at /tmp/buildd/php5-5.4.4/Zend/zend_vm_execute.h:410
#8  0x00007fcf8ca14a92 in xdebug_execute (op_array=0x7fcf90684d90) at /tmp/pear/temp/xdebug/xdebug.c:1435
#9  0x00000000006a095e in zend_execute_scripts (type=8, retval=0x7fcf90684d40, file_count=3) at /tmp/buildd/php5-5.4.4/Zend/zend.c:1279
#10 0x000000000063fe73 in php_execute_script (primary_file=0x0) at /tmp/buildd/php5-5.4.4/main/main.c:2473
#11 0x0000000000749963 in do_cli (argc=0, argv=0x7fff71effe16) at /tmp/buildd/php5-5.4.4/sapi/cli/php_cli.c:988
#12 0x00000000004312aa in main (argc=32767, argv=0x208c480) at /tmp/buildd/php5-5.4.4/sapi/cli/php_cli.c:1361
```

**Comment by sebastianbergmann** [comment]
This extension is [superseded](https://github.com/php-test-helpers/php-test-helpers/issues/29#issuecomment-44049111) by [uopz](https://github.com/krakjoe/uopz) and is no longer maintained.
